In [1]:
import numpy as np
print(np.__version__)

2.3.1


In [2]:
# ---------------------------------------- #

In [3]:
# --- Qn1 --- #

In [4]:
# -- Qn1.1: Create a 1D array of numbers (0 to 11) -- #

In [5]:
q1=np.arange(0, 12, 1)
q1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
# -- Qn1.2: Print the data type of the array -- #

In [7]:
print(q1.dtype)

int32


In [8]:
# -- Qn1.3: Change the dtype to float64 -- #

In [9]:
q1.astype(dtype=np.float64)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [10]:
# ---------------------------------------- #

In [11]:
# --- Qn2 --- #

In [12]:
# -- Qn2.1: Extract All Odd Numbers From Array -- #

In [13]:
a = [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]
a[1::2]

[1, 3, 5, 7, 9, 11]

In [14]:
# ---------------------------------------- #

In [15]:
# --- Qn3 --- #

In [16]:
# -- Qn3.1: Convert a 1D Array to a 2D Array with 2 Rows -- #

In [17]:
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
# ---------------------------------------- #

In [19]:
# --- Qn4 --- #

In [20]:
# -- Qn4.1: Stack Arrays `a` and `b` vertically -- #

In [21]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)

v = np.vstack((a,b))
v

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [22]:
# ---------------------------------------- #

In [23]:
# --- Qn5 --- #

In [24]:
# -- Qn5.1: Get the positions where elements of a and b match -- #

In [25]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a == b)

(array([1, 3, 5, 7]),)

In [26]:
# ---------------------------------------- #

In [27]:
# --- Qn6 --- #

In [28]:
# -- Qn6.1: Swap columns 1 and 2 in the array -- #

In [29]:
a = np.arange(9).reshape(3,3)
print("Array: \n", a)
b=a[:, [0,2,1]]
print("New Array: \n", b)

Array: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
New Array: 
 [[0 2 1]
 [3 5 4]
 [6 8 7]]


In [30]:
# ---------------------------------------- #

In [31]:
# --- Qn7 --- #

In [32]:
# -- Qn7.1: Swap Rows -- #

In [112]:
a = np.arange(9).reshape(3,3)
print("Array: \n", a)
a[[1, 2]] = a[[2, 1]]

print("New Array: \n", a)

Array: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
New Array: 
 [[0 1 2]
 [6 7 8]
 [3 4 5]]


In [107]:
# ---------------------------------------- #

In [108]:
# --- Qn8 --- #

In [36]:
# -- Qn8.1: Reverse -- #

In [115]:
a = np.arange(9).reshape(3,3)
b = a[::-1]
print("New Array: \n", b)

New Array: 
 [[6 7 8]
 [3 4 5]
 [0 1 2]]


In [34]:
# ---------------------------------------- #

In [35]:
# --- Qn9 --- #

In [ ]:
# -- Create 2d array of shape 5x3 containing random dec nums between 5 and 10 -- #

In [81]:
a = np.random.uniform(5, 11, size=15).reshape(5,3) 
a

array([[ 9.59028494,  8.26184825,  9.55619049],
       [ 5.90449348,  5.50946788, 10.55398877],
       [ 9.66120545,  9.62331824,  8.79389133],
       [ 5.89510171,  8.68069416,  6.29155329],
       [ 8.18625615,  8.28044609,  6.91933035]])

In [34]:
# ---------------------------------------- #

In [ ]:
# --- Qn10 --- #

In [125]:
a = np.arange(0, 10, 1) # Given Array

In [82]:
# -- Qn10.1: Create a slice of array contiaining the following values -- #
# [5,6,7]

In [118]:
b = a[5:-2]

array([5, 6, 7])

In [ ]:
# -- Qn10.2: Modify the given array to below format -- #

In [128]:
a[5:8] = 12
a

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [34]:
# ---------------------------------------- #

In [ ]:
# --- Qn11 --- #

In [129]:
# -- Drop all nan values from a 1D numpy array -- #

In [138]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

In [ ]:
# ---------------------------------------- #

In [139]:
# --- Qn12 --- #

In [140]:
# -- Create an Empty, ones and zero array with 6,3, and 4 elements respectively -- #

In [151]:
e = np.empty(6)
o = np.ones(3)
z = np.zeros(4)
print(e)
print(o)
print(z)

[1. 2. 3. 5. 6. 7.]
[1. 1. 1.]
[0. 0. 0. 0.]


In [ ]:
# ---------------------------------------- #

In [ ]:
# --- Qn13 --- #

In [152]:
a = np.full((4,4), 23.67)
a

array([[23.67, 23.67, 23.67, 23.67],
       [23.67, 23.67, 23.67, 23.67],
       [23.67, 23.67, 23.67, 23.67],
       [23.67, 23.67, 23.67, 23.67]])

In [ ]:
# ---------------------------------------- #

In [ ]:
# --- Qn14 --- #

In [153]:
# -- Create an array with 8 values that are spaced linearly in the [13, 27] interval -- #

In [158]:
a = np.linspace(13,27,8, dtype=np.int32)
a

array([13, 15, 17, 19, 21, 23, 25, 27])

In [ ]:
# ---------------------------------------- #

In [159]:
# ---- Optional Questions ---- #

In [ ]:
# --- Qn15 --- #

In [ ]:
# -- Create a random array with 50 random numbers max less than 1000 -- #

In [164]:
a = np.random.randint(0, 1000, 50)
a

array([101, 546, 242, 351, 154, 555,  78,  50, 476, 397, 798,  93, 379,
       520, 705, 269, 519, 588, 707, 577, 837, 182, 908, 859, 543, 538,
       502, 286, 886, 461, 976, 649, 524, 143, 554, 337, 598, 377, 906,
       353, 432, 802, 218, 854, 284, 473, 820, 357, 824, 492])

In [ ]:
# ---------------------------------------- #

In [ ]:
# --- Qn16 --- #

In [ ]:
# -- Improve answer 15 to always return same random numbers -- #

In [176]:
np.random.seed(1)
a = np.random.randint(0, 1000, 50)
print(a)

[ 37 235 908  72 767 905 715 645 847 960 144 129 972 583 749 508 390 281
 178 276 254 357 914 468 907 252 490 668 925 398 562 580 215 983 753 503
 478 864  86 141 393   7 319 829 534 313 513 896 316 209]


In [ ]:
# ---------------------------------------- #

In [177]:
# --- Qn17 --- #

In [ ]:
# -- Generate a 6 letter word from english alph -- #

In [187]:
a = np.array(list('abcdefghijklmnopqrstuvwxyz'), dtype=str)
w = a[a == 'w']
o = a[a == 'o']
r = a[a == 'r']
d = a[a == 'd']
l = a[a == 'l']
y = a[a == 'y']
word = w+o+r+d+l+y
print("First Word: \n", word[0])

# OR

word = ''.join(np.random.choice(a, 6))
print("Second Word: \n", word)

First Word: 
 wordly
Second Word: 
 rzdeyr


In [ ]:
# ---------------------------------------- #

In [188]:
# --- Qn18 --- #

In [ ]:
# -- Create 3 1D Arrays -- #

In [203]:
# -- Solution 1: -- #
d1 = [1,2,3,4,5,6,7,8]
d2 = [9,10,11,12,13,14,15,16]
d3 = [17,18,19,20,21,22,23,24]

x = []
for a,b,c in zip(d1,d2,d3):
    x.append(a+b+c)

y = []
for a,b,c in zip(d1,d2,d3):
    y.append(a-b-c)

print("X: \n", x)
print("Y: \n", y)
print("# ---------------------------------------- #")
# ---------------- #

# -- Solution 2: -- #
d1 = np.arange(1,9)
d2 = np.arange(9,17)
d3 = np.arange(17,25)

a = d1+d2+d3
b = d1-d2-d3

print("A: \n", a)
print("B: \n", b)
# ----------------- #

X: 
 [27, 30, 33, 36, 39, 42, 45, 48]
Y: 
 [-25, -26, -27, -28, -29, -30, -31, -32]
# ---------------------------------------- #
A: 
 [27 30 33 36 39 42 45 48]
B: 
 [-25 -26 -27 -28 -29 -30 -31 -32]


In [ ]:
# ---------------------------------------- #

In [204]:
# --- Qn19 --- #

In [205]:
# -- Calculate IQR for the following array -- #

In [217]:
iqr=np.array([31, 29, 30, 32, 34, 36, 37, 40, 40, 41, 46, 48, 54, 57])

a, b = np.percentile(iqr, [25, 75])
c = b-a
print(c)

12.25


In [ ]:
# ---------------------------------------- #