In [2]:
import numpy as np

In [1]:
# --- Library Book --- #

In [38]:
np.random.seed(1)

# Generate Records
records = np.random.randint(0,6,[2,3,4])
print("Library Records: \n", records)

# Calculate Total Number of Times Each Book Was Borrowed
tbeb = np.sum(records, axis=(0,1))
print("Total Number Of Each Book Borrowed: \n", tbeb)

# Identify the student who borrowed the most number of books
tbbes = np.sum(records, axis=(0,2))

# Most Active Student
max = np.argmax(tbbes) + 1
print("Total Borrowed by Each Student: \n", max)



Library Records: 
 [[[5 3 4 0]
  [1 3 5 0]
  [0 1 4 5]]

 [[4 1 2 4]
  [5 2 4 3]
  [4 2 4 5]]]
Total Number Of Each Book Borrowed: 
 [19 12 23 17]
Total Borrowed by Each Student: 
 3
