
# Excercise: NumPy EDA Excercise

We will generate a small numeric dataset and practice basic NumPy operations seen in class.  


In [254]:

# Imports
import numpy as np




## 1) Generate a numeric dataset

We create 500 rows with 6 columns:  
`[day, item, price, qty, discount, paid]`

- Reproducible seed (`np.random.seed`)  
- Discrete sampling (`np.random.choice`, `np.arange`)  
- Continuous values (`np.random.uniform`)  
- Stack columns (`np.column_stack`)


In [255]:
# Reproducible
np.random.seed(42)

In [256]:
# Sizes
N       = 500
n_days  = 30
n_items = 50

In [257]:
# Columns
# TODO : Use Random Choice inside of it np.arange with number of days, size is N     #0..29
day      = np.random.choice(np.arange(0, n_days), N)
day

array([ 6, 19, 28, 14, 10,  7, 28, 20,  6, 25, 18, 22, 10, 10, 23, 20,  3,
        7, 23,  2, 21, 20,  1, 23, 11, 29,  5,  1, 27, 20,  0, 11, 25, 21,
       28, 11, 24, 16, 26, 26,  9, 27, 27, 15, 14, 29, 29, 14, 29, 18, 11,
       22, 19, 24,  2,  4, 18,  6, 20,  8,  6, 17,  3, 24, 27, 13, 17, 25,
        8, 25, 20,  1, 19, 27, 14, 27,  6, 11, 28,  7, 14,  2, 13, 16,  3,
       17,  7,  3,  1, 29,  5, 21,  9,  3, 21, 28, 17, 25, 11,  1,  9, 29,
        3, 13, 15, 14,  7, 13, 22, 27, 24, 29,  7, 20, 15, 12, 17, 14, 20,
       23, 25, 24, 27, 27, 27, 12,  8, 28, 14, 12,  0, 24,  6,  8, 23,  0,
       11,  7, 23, 10, 18, 16,  7,  2,  2,  0, 26,  4,  9,  6, 25,  8, 27,
        6,  8,  7, 11,  1,  0, 15, 22, 22, 29, 23,  4,  2, 11,  7, 21, 26,
        2,  0,  2,  4, 14, 13,  2,  0,  4, 25, 22, 13,  6, 26,  8, 14, 14,
       25,  9, 27, 12, 18,  6, 16, 19, 28,  3, 29,  4, 22,  6, 12, 14, 10,
       28,  3, 12,  6, 26, 18, 21, 27,  1,  9, 12, 29, 24, 20,  5, 27, 27,
       11, 11, 19, 29, 29

In [258]:

# TODO : Use Random Choice inside of it np.arange with number of items, size is N        # 0..49
item     =    np.random.choice(np.arange(0, n_items), N)
item

array([41, 25, 34, 49, 24, 23, 12,  6, 35, 44, 19,  0,  7, 45, 15, 13, 11,
       22, 14, 27, 33,  1, 31, 22, 21, 24, 21, 21, 48, 41,  5, 14, 42, 36,
       32,  7, 43, 43,  4, 38,  3,  5, 44, 31, 29, 46, 34, 39, 15, 12, 49,
       41, 29, 18, 16, 18, 27, 25, 36, 25, 22,  8, 11,  0,  0, 46, 33, 31,
       47, 24, 39, 44,  0, 15, 38,  4, 21, 28,  2, 11, 25, 15, 36, 21, 28,
       13, 27,  4, 46, 48, 29, 45,  4, 11, 15, 25, 25, 47, 20, 38, 35, 32,
       29, 36, 22,  9,  4, 35, 33, 30,  9, 18, 31,  0,  4, 44,  3, 15, 23,
       15,  1, 48, 27, 31, 26, 19, 23, 11, 49, 34, 32, 32, 42, 36, 11,  2,
        0, 32, 39,  9, 42, 43, 28, 12, 11, 30, 45,  1, 49, 34, 22, 16, 25,
        7, 28, 25,  9, 25, 33, 40,  6,  3, 49, 44, 10, 28, 35, 24, 20, 35,
        9, 36,  8, 23, 34, 48, 34, 47, 35, 17, 48, 38, 31, 23, 22, 31, 36,
       11, 48, 12, 22, 24, 34, 40, 29, 16, 48, 19, 47, 24, 21, 12, 18, 48,
       35, 11, 40, 18, 11,  8,  6, 27, 13, 30, 18, 46, 15,  4, 34, 11, 24,
       20, 35, 22, 15, 38

In [259]:

# TODO : Use Random uniform from 5 to 50 with size N                # price (float)
price    = np.random.uniform(5, 50, N)
price

array([20.64286465,  6.43121067, 29.69218891, 29.04905767, 21.01961679,
       45.23977683, 10.79367792, 19.8544781 , 19.47122441,  9.15307638,
       26.65154273, 35.95031227, 28.02456561, 12.06399572, 21.97786844,
        5.1167761 , 44.07354982,  8.80326535, 31.8775137 , 49.38156481,
       29.14657907, 46.58187916, 15.62524399, 39.1979934 , 28.90695893,
       37.42322276,  7.80536131, 11.64825914, 10.99026179, 35.92244774,
       42.99983027, 38.73273044,  6.37124687, 44.02467415, 20.93660019,
       22.87237246,  9.71911249, 38.18323427, 13.20277453, 30.37842914,
       42.83194936,  9.01419479, 29.09010038, 15.49473852, 20.43170889,
       26.32864736, 20.97969365, 34.19702781, 26.58119458, 31.28897681,
       38.15701139, 30.09840197, 31.39409456, 30.40063441, 22.04476817,
       20.18510752, 45.48413287, 32.339985  , 15.995892  , 27.4211464 ,
       19.86568166, 47.01613207,  5.33904634, 15.1399759 , 21.44105689,
       26.95144104, 43.2867883 ,  8.9549431 , 41.2639199 ,  7.50

In [260]:

# TODO : Use Random Choice inside of it numpy array [1,2,3,4,5], size is N        # quantity (int-like)
qty      =  np.random.choice(np.array([1,2,3,4,5]), N)
qty

array([1, 1, 3, 4, 2, 1, 5, 3, 2, 3, 2, 2, 1, 3, 3, 5, 5, 1, 1, 4, 5, 2,
       3, 1, 3, 3, 4, 5, 1, 3, 1, 2, 4, 2, 1, 1, 5, 3, 3, 2, 4, 3, 5, 2,
       2, 5, 4, 5, 4, 5, 5, 1, 2, 5, 5, 3, 2, 3, 2, 3, 5, 5, 1, 3, 4, 1,
       3, 3, 1, 5, 3, 5, 1, 5, 2, 4, 3, 4, 5, 3, 5, 2, 1, 3, 2, 2, 3, 5,
       2, 4, 2, 5, 5, 4, 2, 5, 3, 1, 1, 1, 2, 4, 5, 3, 3, 2, 1, 2, 4, 4,
       5, 5, 4, 4, 4, 2, 4, 3, 1, 4, 1, 2, 1, 2, 3, 2, 2, 5, 4, 4, 3, 3,
       4, 5, 4, 5, 3, 1, 3, 3, 2, 2, 2, 2, 5, 4, 1, 3, 5, 1, 5, 5, 3, 4,
       2, 4, 3, 3, 3, 1, 4, 4, 5, 5, 5, 3, 4, 3, 1, 5, 3, 3, 1, 2, 4, 2,
       5, 3, 1, 1, 4, 2, 4, 3, 4, 1, 1, 5, 5, 3, 2, 4, 3, 5, 4, 5, 4, 2,
       3, 4, 1, 1, 4, 4, 4, 1, 1, 4, 5, 5, 2, 3, 5, 1, 5, 2, 2, 3, 5, 1,
       1, 4, 1, 3, 3, 1, 1, 4, 1, 4, 4, 1, 2, 2, 4, 1, 2, 1, 1, 1, 5, 1,
       5, 4, 2, 2, 2, 2, 2, 2, 2, 4, 1, 3, 5, 3, 3, 1, 1, 1, 2, 4, 2, 4,
       4, 3, 3, 4, 4, 2, 2, 3, 1, 4, 2, 3, 2, 4, 4, 5, 1, 5, 3, 2, 3, 4,
       5, 5, 5, 3, 4, 2, 2, 3, 5, 1, 3, 3, 4, 2, 3,

In [261]:

# TODO : Use Random uniform from 0 to 5 with size N                        # discount (float)
discount = np.random.uniform(0, 5, N)
discount

array([2.72843444e+00, 2.22209726e+00, 7.33352852e-02, 2.93530854e+00,
       8.42221926e-01, 3.21287984e+00, 3.79672164e+00, 2.50222655e+00,
       2.71181832e+00, 4.75739280e+00, 4.23583681e+00, 4.57118258e+00,
       4.06883144e+00, 5.44591709e-01, 7.44959280e-01, 2.63311899e+00,
       1.23034829e+00, 2.38347738e+00, 1.97182662e+00, 2.74707119e+00,
       3.73437858e+00, 3.57745454e+00, 2.60617066e+00, 4.11196709e+00,
       2.15431046e+00, 4.48357145e+00, 3.56401350e-01, 4.77330015e+00,
       3.27346541e+00, 1.90037254e+00, 9.85770633e-01, 2.39591615e+00,
       9.72791616e-01, 8.31658039e-01, 3.08675879e+00, 2.61542362e+00,
       3.35048017e+00, 4.64802939e+00, 2.66130107e+00, 2.90466027e+00,
       4.48131696e-01, 3.58817893e+00, 1.99952603e+00, 4.88362619e+00,
       4.11587008e+00, 2.61240520e+00, 6.16113271e-01, 4.29707897e+00,
       3.99890548e+00, 9.22925648e-01, 1.47639145e+00, 3.96703629e+00,
       9.26142233e-01, 4.58876245e+00, 2.12263713e+00, 4.35194813e-01,
      

In [262]:

# TODO : Use Random Choice inside of it numpy array [0,1], size is N           # 0=cancel, 1=paid
paid     = np.random.choice(np.array([0,1]), N)
paid

array([0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,

In [263]:

# TODO : Assemble design matrix (note: dtype will be float due to float columns) , hint use column stack
X = np.column_stack((day, item, price, qty, discount, paid))
X

array([[6.00000000e+00, 4.10000000e+01, 2.06428647e+01, 1.00000000e+00,
        2.72843444e+00, 0.00000000e+00],
       [1.90000000e+01, 2.50000000e+01, 6.43121067e+00, 1.00000000e+00,
        2.22209726e+00, 1.00000000e+00],
       [2.80000000e+01, 3.40000000e+01, 2.96921889e+01, 3.00000000e+00,
        7.33352852e-02, 1.00000000e+00],
       ...,
       [1.50000000e+01, 4.00000000e+00, 4.21792563e+01, 1.00000000e+00,
        4.54695096e+00, 0.00000000e+00],
       [6.00000000e+00, 1.70000000e+01, 4.10346359e+01, 1.00000000e+00,
        3.90106532e+00, 1.00000000e+00],
       [2.80000000e+01, 2.70000000e+01, 3.33400065e+01, 1.00000000e+00,
        3.51460191e-02, 0.00000000e+00]])

In [264]:
print("Shape (rows, cols):", X.shape)
print("First 5 rows:")
print(np.round(X[:5], 2))
print("\nColumn order = [day, item, price, qty, discount, paid]")


Shape (rows, cols): (500, 6)
First 5 rows:
[[ 6.   41.   20.64  1.    2.73  0.  ]
 [19.   25.    6.43  1.    2.22  1.  ]
 [28.   34.   29.69  3.    0.07  1.  ]
 [14.   49.   29.05  4.    2.94  1.  ]
 [10.   24.   21.02  2.    0.84  1.  ]]

Column order = [day, item, price, qty, discount, paid]



## 2) Introduce missing values (NaNs) in **`price`** column

Pick **`price`** column and set a few entries to `NaN` to simulate messy data.  





In [265]:

# TODO : Choose 15 random row indices , use random.choice, inside of it arange(N) and size = 15)
nan_idx =  np.random.choice(np.arange(N), 15)
nan_idx


array([431, 157, 267,  34, 266,  63, 493,  49, 468, 254, 148, 324, 303,
       275, 356])

In [266]:

## ? Google isnan method
# TODO : Add NaNs to chosen column <- `a[np.isnan(a)]`
price[nan_idx] = np.nan
price

array([20.64286465,  6.43121067, 29.69218891, 29.04905767, 21.01961679,
       45.23977683, 10.79367792, 19.8544781 , 19.47122441,  9.15307638,
       26.65154273, 35.95031227, 28.02456561, 12.06399572, 21.97786844,
        5.1167761 , 44.07354982,  8.80326535, 31.8775137 , 49.38156481,
       29.14657907, 46.58187916, 15.62524399, 39.1979934 , 28.90695893,
       37.42322276,  7.80536131, 11.64825914, 10.99026179, 35.92244774,
       42.99983027, 38.73273044,  6.37124687, 44.02467415,         nan,
       22.87237246,  9.71911249, 38.18323427, 13.20277453, 30.37842914,
       42.83194936,  9.01419479, 29.09010038, 15.49473852, 20.43170889,
       26.32864736, 20.97969365, 34.19702781, 26.58119458,         nan,
       38.15701139, 30.09840197, 31.39409456, 30.40063441, 22.04476817,
       20.18510752, 45.48413287, 32.339985  , 15.995892  , 27.4211464 ,
       19.86568166, 47.01613207,  5.33904634,         nan, 21.44105689,
       26.95144104, 43.2867883 ,  8.9549431 , 41.2639199 ,  7.50

In [267]:

# TODO : Reflect the changes back into the whole matrix X
X[:, 2] = price
X

array([[6.00000000e+00, 4.10000000e+01, 2.06428647e+01, 1.00000000e+00,
        2.72843444e+00, 0.00000000e+00],
       [1.90000000e+01, 2.50000000e+01, 6.43121067e+00, 1.00000000e+00,
        2.22209726e+00, 1.00000000e+00],
       [2.80000000e+01, 3.40000000e+01, 2.96921889e+01, 3.00000000e+00,
        7.33352852e-02, 1.00000000e+00],
       ...,
       [1.50000000e+01, 4.00000000e+00, 4.21792563e+01, 1.00000000e+00,
        4.54695096e+00, 0.00000000e+00],
       [6.00000000e+00, 1.70000000e+01, 4.10346359e+01, 1.00000000e+00,
        3.90106532e+00, 1.00000000e+00],
       [2.80000000e+01, 2.70000000e+01, 3.33400065e+01, 1.00000000e+00,
        3.51460191e-02, 0.00000000e+00]])

In [268]:

print("NaN indices (price):", nan_idx[:10])
print("Sample price values with NaNs:", price[nan_idx[:5]])


NaN indices (price): [431 157 267  34 266  63 493  49 468 254]
Sample price values with NaNs: [nan nan nan nan nan]



## 3) Simple clean-up using masks

- Detect NaNs with `np.isnan`  
- Impute them with `0.0` using `np.where`
- Update the table `X`


In [269]:

# TODO :  Detect NaNs in price , Hint ## Google isnan method
is_nan_price = np.isnan(price)
print("NaN count in price:", int(is_nan_price.sum()))

NaN count in price: 15


In [270]:

# TODO : Replace NAN with 0.0 otherwise the price
price = np.where(is_nan_price, 0.0, price)

In [271]:
# Update X with the new price
X[:, 2] = price

In [272]:

# Quick check
print("After impute — NaN count in price:", int(np.isnan(price).sum()))


After impute — NaN count in price: 0



## 4) Basic summaries

- Number of paid rows (`np.where(...).size`)  

- Average **qty** for paid rows


In [273]:

## TODO : obtain the paid idx only using np.where
paid_idx = np.where(price) 

# TODO : Get the size the paid indecies, search for .size
num_paid = np.size(paid_idx)

In [274]:

avg_qty_paid = qty[paid_idx].mean() if num_paid>0 else 0.0

print("Paid rows:", num_paid, "of", N)
print("Average qty (paid rows):", round(avg_qty_paid, 2))


Paid rows: 485 of 500
Average qty (paid rows): 2.98



## 5) Slicing & masks

- Select rows where `day in [10, 14]`  
- Replace all `qty == 1` with `2` using `np.where`  
- Find indices where `qty == 5` **and** `paid == 1`


In [278]:

## TODO : Select rows where day in [10, 14]
mid_rows = np.where(np.isin(day, [10, 14]))[0]
print("Rows where day in [10,14]:", mid_rows.size)
print(np.round(X[mid_rows[:5]], 2))

Rows where day in [10,14]: 26
[[14.   49.   29.05  4.    2.94  1.  ]
 [10.   24.   21.02  2.    0.84  1.  ]
 [10.    7.   28.02  1.    4.07  0.  ]
 [10.   45.   12.06  3.    0.54  1.  ]
 [14.   29.   20.43  2.    4.12  0.  ]]


In [ ]:
# TODO Replace qty==1 with 2
qty = 
X[??] = qty #TODO Replace in x
print("Changed qty==1 -> 2. Sample qty values:", qty[:10])

SyntaxError: invalid syntax (1787542217.py, line 2)

In [ ]:
# TODO Positions where qty==5 AND paid==1
hit = ?? [0]
print("Indices with qty==5 and paid==1 (first 10):", hit[:10])



## 6) 2D array play — `reshape`, swap rows/cols, reverse, stack

- Take the first 12 rows × 3 columns (`day,item,price`)  
- `reshape` to 4×9  
- Swap the first two **columns** (use `np.copy`)  
- Swap the first two **rows**  
- Reverse rows with `np.flipud`  
- Vertically stack the result with itself (`np.vstack`)


In [ ]:
tiny = ??      # TODO copy the first 12 rows × 3 columns (day,item,price )
A = tiny.??        # TODO reshape 4×9


In [ ]:
print("A shape:", A.shape)
print("A (first 2 rows):\n", np.round(A[:2], 2))

In [ ]:
# TODO Swap first two columns
A_copy = ??
A[:, 0] = ??
A[:, 1] =??
print("\nAfter swapping first two columns (first 2 rows):\n", np.round(A[:2], 2))

In [ ]:
# TODO Swap first two rows
A2 = np.copy(A)
A[0, :], A[1, :] = ??
print("\nAfter swapping first two rows (first 2 rows):\n", np.round(A[:2], 2))

In [ ]:
# TODO Reverse rows
A = ??
print("\nAfter reversing rows (first 2 rows):\n", np.round(A[:2], 2))

In [ ]:
# Stack A with itself versically
A_stacked = ??
print("\nStacked shape:", A_stacked.shape)



## 7) Percentile threshold on `price`

- Use `np.percentile` to compute the 90th percentile of **price** among paid rows  
- Flag rows where `price >= p90`  



In [ ]:
paid_price = price[paid==1] ## TODO : obtain price for paid ==1

In [ ]:
p90 = ?? #TODO search how to obtain percentile 90

In [ ]:
flag_hi = ?? [0] # TODO : Flag rows where price >= p90

In [ ]:
print(f"90th percentile of price (paid rows): {p90:.2f}")
print("First 10 high-price indices:", flag_hi[:10])



## 8) Linspace & simple binning for `price`

- Create evenly spaced **price checkpoints** with `np.linspace`  



In [ ]:

# Price checkpoints
checkpoints = ??  # Create evenly spaced price checkpoints with linespace (GOOGLE)
print("Price checkpoints:", np.round(checkpoints, 2))





## 9) What You Practiced

- Random data: `np.random.seed`, `np.random.choice`, `np.random.uniform`, `np.arange`  
- Masking & replacement: `np.where`, `np.isnan`  
- 2D shaping: `reshape`, `np.copy`, row/column swaps, `np.flipud`, `np.vstack`  
- Simple stats: `np.percentile`, basic sums and means  
- Utilities: `np.linspace`
